### ISSUE TITLE
Unable to setup custom polygon shaped fly zone 

### ISSUE THREAD

**Issue by dhruvappstack** [DJI-Mobile-SDK-Tutorials/iOS-GEODemo#2]
I am working on app in which i have to make custom polygon shaped fly zone .But according to sdk api i can apply  restriction on flight radius ( fly zone distance upto which it can move).I want my app to restrict the zone to fly within the polygon shaped region .
![zone](https://cloud.githubusercontent.com/assets/13067085/20552819/a6b43b42-b174-11e6-8faa-769186f4627a.png)

**Comment by oliverou** [comment]
Hi @EonKid, please see my reply in iOS-GSDemo Github repo's issue: <https://github.com/DJI-Mobile-SDK-Tutorials/iOS-GSDemo/issues/6>. Thanks!
