### ISSUE TITLE
Unable to use automatically go to home location or takeofff location during flight

### ISSUE THREAD

**Issue by dhruvappstack** [DJI-Mobile-SDK-Tutorials/iOS-GEODemo#3]
I am using DJI SDK 3.4 .I want to land at home point or takeoff point but when the aircraft have travelled some distance and i am also setting maximum radius 500.But when i use function goToHomelocation function it is giving error "error: over maximum radius".I can land to its home point  when the drone is within the 30 m from takeoff point  .Please help me as soon as possible.My app is in the final phase.

**Comment by XietongLU** [comment]
Could you give us the exact description of the error? Because we cannot find "error: over maximum radius" in our code base.

**Comment by dhruvappstack** [comment]
Thanks @XietongLU  i found this error as i am setting the maximum radius more than 500m which is more than  the flight limitation
